### ISSUE TITLE
CAD is not properly installing

### ISSUE THREAD

**Issue by Caleb-J773** [Dev-CasperTheGhost/snaily-cadv2#15]
After following the installation steps, when I reach the `**npm run create**`, at the very end, it appears to have failed to build **node_modules\bcrypt**

```
> bcrypt@4.0.1 install C:\Users\Caleb\Documents\snaily-cadv2\server\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

'node-pre-gyp' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Caleb\AppData\Roaming\npm-cache\_logs\2020-07-05T00_28_30_364Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snailycad-v2@1.5.5 create: `npm install --prefix client && npm install --prefix server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snailycad-v2@1.5.5 create script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Caleb\AppData\Roaming\npm-cache\_logs\2020-07-05T00_28_30_517Z-debug.log
```

I do have the required yarn and npm properly installed, I also reinstalled node.js/npm to verify this isn't a corrupted cache.

**Comment by casperiv0** [comment]
Hey!

Try to install `bcrypt` (package that is not installing correctly) individually, to do that run: 

`cd server`
`npm install bcrypt`

**Comment by Caleb-J773** [comment]
That appears to fix the first build, but then when I proceed to the next steps, I get this

```
Error [BrowserslistError]: C:\Users\Caleb\Documents\snaily-cadv2\client contains both browserslist and package.json with browsers
    at C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:303:15
    at eachParent (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:48:18)
    at Object.findConfig (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:279:20)
    at Function.loadConfig (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:212:37)
    at checkBrowsers (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\browsersHelper.js:45:32)
    at Object.<anonymous> (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-scripts\scripts\build.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  browserslist: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Caleb\AppData\Roaming\npm-cache\_logs\2020-07-05T13_04_13_528Z-debug.log

```

This occurs when running the 
```
Run cd client
Run npm run build To create a build folder
```
portion of the installation steps.

**Comment by casperiv0** [comment]
remove the `node_modules` folder in the client folder via File Explorer, then try installing the client packages using `yarn`, `yarn install` and  `yarn build`

**Comment by Caleb-J773** [comment]
Still getting the rather same error, the same error with the browserslist.
I ran yarn install after removing the node modules, which it installed and worked fine. Then I go to run yarn build and it fails with with the browserslist. 

```
C:\Users\Caleb\Documents\snaily-cadv2\client>yarn build
yarn run v1.22.4
$ react-scripts build

Error [BrowserslistError]: C:\Users\Caleb\Documents\snaily-cadv2\client contains both browserslist and package.json with browsers
    at C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:303:15
    at eachParent (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:48:18)
    at Object.findConfig (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:279:20)
    at Function.loadConfig (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\node_modules\browserslist\node.js:212:37)
    at checkBrowsers (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-dev-utils\browsersHelper.js:45:32)
    at Object.<anonymous> (C:\Users\Caleb\Documents\snaily-cadv2\client\node_modules\react-scripts\scripts\build.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  browserslist: true

error Command failed with exit code 1.
```

Here's the yarn install process
```
yarn install v1.22.4le (internal/modules/cjs/loader.js:1138:30)
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear th
warning " > react-thunk@1.0.0" has incorrect peer dependency "react@~0.14.0 || ^15.0.0".
[4/4] Building fresh packages...
Done in 95.30s.
```

**Comment by casperiv0** [comment]
I have no clue why this would be happening, try to run yarn add browserslist to install the latest version of browserlist and then try to build it again using yarn. I'll look for some help on why this is happening.

**Comment by casperiv0** [comment]
> I have no clue why this would be happening, try to run yarn add browserslist to install the latest version of browserlist and then try to build it again using yarn. I'll look for some help on why this is happening.

I found the issue, I pushed an update with new installation steps. Make sure to delete all node_module folders:

 /node_modules
/client/node_modules
/server/node_modules

and then follow the new steps: https://github.com/Dev-CasperTheGhost/snaily-cadv2#readme

Let me know if that works!

**Comment by Caleb-J773** [comment]
That seems to have worked until we get to the part of npm start heh.

Then serve apparently gives trouble.

`[1] > serve -s build -l 80
[1]
[1] 'serve' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! client@0.1.0 serve: `serve -s build -l 80`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the client@0.1.0 serve script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Which then I believe causes the webpage to not load at all.
``Cannot GET /`

**Comment by Caleb-J773** [comment]
![image](https://user-images.githubusercontent.com/4467576/86598998-06391980-bf6c-11ea-9a4d-d4ed2b30f5a7.png)

I fixed the issue with yarn by doing yarn add serve to the client folder manually.
However the page is still not loading (picture above), no errors in console now.

**Comment by casperiv0** [comment]
can you see if there's an error in the browsers console?

**Comment by Caleb-J773** [comment]
One moment, let me check.

**Comment by Caleb-J773** [comment]
![image](https://user-images.githubusercontent.com/4467576/86599597-d76f7300-bf6c-11ea-8a2e-d3ed844eb89e.png)

These are the only two errors in the console

**Comment by casperiv0** [comment]
Alright I think why this is happening sorry, I'll push a fix in one sec.

**Comment by casperiv0** [comment]
Just pushed the fix, make sure to run `yarn build` in the client folder after running `git pull`..

**Comment by Caleb-J773** [comment]
Okay, let me do that and I'll get back to with the result

**Comment by Caleb-J773** [comment]
Looks like that worked and got it displaying everything, I'm running through the cad to make sure all the pages and things are loading in properly.

**Comment by casperiv0** [comment]
Alright sounds good, let me know if you find anything else.

**Comment by Caleb-J773** [comment]
Everything works perfectly, thank you so much for helping me out, have a great week

**Comment by casperiv0** [comment]
Thankyou, you too!
